### ISSUE TITLE
Feature request: implement left shift on field elements

### ISSUE THREAD

**Issue by therealyingtong** [zkcrypto/ff#60]
e.g. `F::one() << 63` would be equivalent to `F::from_u64(1 << 63)`.

**Comment by str4d** [comment]
The problem here is that people will have different interpretations of what this operation does. `F::from_u64(1 << 63)` is most commonly used to create a field element that is some power-of-two, and the most efficient way to do that on an existing field element is doubling. However, doubling a finite field element is not the same as a left-shift, and the latter would be _significantly_ more expensive (serialize to bytes, left-shift, mask to a valid finite field element somehow, then parse).

**Comment by str4d** [comment]
I'm not going to implement this without some strong motivating use cases.
